### ISSUE TITLE
Why the files I get are all in edf format. And can't be opened with normal edf software?

### ISSUE THREAD

**Issue by ddxy2021** [quenotl/PARESIS#2]
I want to get the image of the speckle before and after, but I only get the edf file, I have set all the parameters, is this correct, how to open the edf file?

**Comment by quenotl** [comment]
Hello,
We usually work with .edf so we just used this format by default. We open the .edf files with the ESRF plug-in on imageJ. (https://www.esrf.fr/UsersAndScience/Experiments/Imaging/ID19/Software/slice-by-slice-volume-opener)

If it is more convenient to you, I have added an option to save the images as .tif instead of .edf. You now have an option in the main.py that il called 'saving_format'. You will also need to download the new InputOutput folder for it to work.  
Hope that helps, have a nice day.
